#@data/values
---
git_uri: git@github.com:blinkbitcoin/blink.git
git_branch: main
git_charts_uri: git@github.com:blinkbitcoin/charts.git
<<<<<<< HEAD
git_stablesats_uri: git@github.com:GaloyMoney/stablesats-rs.git
git_price_realtime_uri: git@github.com:blinkbitcoin/price.git
git_price_history_uri: git@github.com:blinkbitcoin/price.git
git_bria_uri: git@github.com:GaloyMoney/bria.git
=======
git_stablesats_uri: git@github.com:blinkbitcoin/stablesats-rs.git
git_price_realtime_uri: git@github.com:blinkbitcoin/price.git
git_price_history_uri: git@github.com:blinkbitcoin/price.git
git_bria_uri: git@github.com:blinkbitcoin/bria.git
>>>>>>> upstream/main
git_charts_branch: main
git_charts_bot_branch: bot-bump-galoy-image
git_stablesats_proto_bot_branch: bot-bump-stablesats-proto
git_price_history_proto_bot_branch: bot-bump-price-history-proto
git_price_realtime_proto_bot_branch: bot-bump-price-realtime-proto
git_bria_api_proto_bot_branch: bot-bump-bria-api-proto
github_private_key: ((github-blinkbitcoin.private_key))
github_token: ((github-blinkbitcoin.api_token))
github_app_id: ((github-blinkbitcoin.github_app_id))
github_app_private_key: ((github-blinkbitcoin.github_app_private_key))
docker_registry: us.gcr.io/galoy-org
docker_registry_user: ((docker-creds.username))
docker_registry_password: ((docker-creds.password))
docker_host_ip: ((staging-ssh.docker_host_ip))
artifacts_bucket_name: ((staging-gcp-creds.bucket_name))
staging_inception_creds: ((staging-gcp-creds.creds_json))
staging_ssh_private_key: ((staging-ssh.ssh_private_key))
staging_ssh_pub_key: ((staging-ssh.ssh_public_key))
git_version_branch: version
gh_org: blinkbitcoin
gh_repository: blink

slack_channel: galoy-main-github
slack_username: concourse
slack_webhook_url: ((galoy-main-slack.api_url))
